
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://223.80.105.201:13307/cba?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: cas@!23
    hikari:
      poolName: Hikari
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.casair.cba_work
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jhipster:
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        base64-secret: ZDMzN2MxNzk3MDZkN2MyNmU0YTczNmJkMDkxMTM0OTM1NWE0MmQ2Y2M0NTg1Yzk1OWVjYjZmNDkxNWQ5MjhmMjFlOThhOTU2MGZlMzYzOGE5MTlhMTI1M2FmZmI3Y2M3ODM4Zjc1YWU2NDBmMjVjODYzYjg1M2QxYjM2YWE4Y2U
        token-validity-in-seconds: 864000000
        token-validity-in-seconds-for-remember-me: 2592000000